polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

pybursa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import index, contact, student_list, student_detail
from feedbacks import views


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^contact/',  contact, name='contact'),
    url(r'^feedback/',  views.FeedbackView.as_view(), name='feedback'),
    url(r'^quadratic/', include('quadratic.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^courses/', include('courses.urls', namespace = 'courses', app_name='courses')),
    url(r'^students/', include('students.urls', namespace = 'students', app_name='students')),
    url(r'^coaches/', include('coaches.urls', namespace = 'coaches', app_name='coaches')),
    url(r'^admin/', admin.site.urls),
]

students/urls.py
from django.conf.urls import url
from . import views

app_name = 'students'
urlpatterns = [
url(r'^$', views.StudentListView.as_view(), name='list_view'),
url(r'^(?P<pk>\d+)/$', views.StudentDetailView.as_view(), name='detail'),
url(r'^add/$', views.StudentCreateView.as_view(), name='add'),
url(r'^edit/(?P<pk>\d+)/$', views.StudentUpdateView.as_view(), name='edit'),
url(r'^remove/(?P<pk>\d+)/$', views.StudentDeleteView.as_view(), name='remove'),
]

students/models.py
from django.db import models
from django.conf import settings
from courses.models import Course

class Student(models.Model):
    name=models.CharField(max_length=60)         
    surname=models.CharField(max_length=60)     
    date_of_birth=models.DateField()    
    email=models.EmailField()
    phone=models.CharField(max_length=15)   
    address=models.CharField(max_length=255)      
    skype=models.CharField(max_length=25)
    courses=models.ManyToManyField(Course)   

    def full_name(self):
        self.full_n = self.name + " " + self.surname
        return self.full_n
    def __str__(self):
        return self.full_name()
    

students/forms.py
from students.models import Student
from django import forms

class StudentModelForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'surname', 'date_of_birth', 'email', 'phone', 'address', 'skype','courses']

students/views.py
from django.shortcuts import render, redirect, get_object_or_404
from students.models import Student
from .forms import StudentModelForm
from django.contrib import messages
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy

import logging
logger = logging.getLogger(__name__)

class StudentListView(ListView):
    model = Student
    paginate_by = 2
 
    def get_queryset(self):
       qs = super().get_queryset()
       course_id = self.request.GET.get('course_id', None)
       if course_id:
           qs = qs.filter(courses__id=course_id)
       return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course_id = self.request.GET.get('course_id', None)
        if course_id:
            context['course_id_url'] = 'course_id={}&'.format(self.request.GET.get('course_id', None)) 
        return context

class StudentDetailView(DetailView):
    model = Student
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        logger.debug("Students detail view has been debugged!")
        logger.info("Logger of students detail view informs you!")        
        logger.warning("Logger of students detail view warns you!")
        logger.error("Students detail view went wrong!")
        return context
  


class StudentCreateView(CreateView):
    model = Student
    form_class = StudentModelForm
    success_url = reverse_lazy('students:list_view')
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Student {0} has been successfully added.".format(form.cleaned_data['name'] + ' ' + form.cleaned_data['surname']))
        return response
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Student registration' 
        return context
    
class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentModelForm
    success_url = reverse_lazy('students:list_view')
    
    def get_success_url(self):
        super().get_success_url()
        pk = self.kwargs['pk']
        return reverse('students:edit', args=(pk,))

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Info on the student has been successfully changed.")
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Student info update' 
        return context


class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy('students:list_view')
    
    def delete(self, request, *args, **kwargs):
        response = super().delete(self, request, *args, **kwargs)
        messages.success(self.request, "Info on {0} has been successfully deleted.".format(
            self.object.name + ' ' + self.object.surname))
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Student info suppression' 
        return context





# Create your views here.

templates/students/student_confirm_delete.html
{% extends "base.html" %}

{% block nav_class_student %} active {% endblock %}

{% block title %}  {{ title }}  {% endblock title %}


{% block content %}
      
 <div class="blog-post">
  <h2>Студент {{ student }} будет удален </h2>

   <form method="post">
     {% csrf_token %}
     <input type="submit" value = "Удалить"/>
   </form>

{% endblock content %}

templates/students/student_detail.html
{% extends "base.html" %}


{% block nav_class_student %} active {% endblock %}


{% block title %} О студенте {% endblock title %}


{% block content %}
     <h1>{{ student.name }} {{ student.surname }}</h1>
       
      <div class="row">

          <div class="blog-post">
     
          <table class="table table-bordered", style="width: 50%">
         
            <tr><td class="student_info">дата рождения</td><td>{{ student.date_of_birth }}</td></tr>
            <tr><td class="student_info">адрес</td><td>{{ student.address }}</td></tr>
            <tr><td class="student_info">email</td><td>{{ student.email }}</td></tr>
            <tr><td class="student_info">skype</td><td>{{ student.skype }}</td></tr>
            <tr><td class="student_info">телефон</td><td>{{ student.phone }}</td></tr>
            <tr><td class="student_info">курсы</td>
                 <td>{% for courses in student.courses.all %}
                       <p><a href="{% url 'courses:detail' courses.id%}">{{ courses }}</a></p>
                     {% endfor %} 
                  </td></tr>
          
          </table>

          </div><!-- /.blog-post -->      
        
      </div><!-- /.row -->
{% endblock content %}




templates/students/student_form.html
{% extends "base.html" %}

{% block nav_class_student %} active {% endblock %}

{% block title %} {{ title }} {% endblock title %}


{% block content %}
{% if messages %}
<ul class="messages">
 <div class="jumbotron">
   {% for message in messages %}
     <li{% if message.tags %} class="{{ massage.tags }}" {% endif %}>{{ message }}</li>
   {% endfor %}
</div>
</ul>
{% endif %}
      
 <div class="blog-post">
  <h2>{{ title }}</h2>

   <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value = "Сохранить"/>
   </form>

{% endblock content %}

templates/students/student_list.html
{% extends "base.html" %}

{% block nav_class_student %} active {% endblock %}

{% block title %} Список студентов {% endblock title %}


{% block content %}
{% if messages %}
<ul class="messages">
    <div class="jumbotron">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ massage.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </div>
</ul>
{% endif %}

<p>
  <a href="{% url 'students:add' %}"><button type="button" class="btn btn-primary">Добавить нового студента</button></a>
</p>

      <div class="blog-post">
            <h2>Список студентов </h2>

            <table class="table table-bordered" style="width: 95%">
                <tr class="student_list">
                    <td>#</td>
                    <td>фамилия имя</td>
                    <td>адрес</td>
                    <td>skype</td>
                    <td>курсы</td>
                    <td></td>
                    <td></td>
                </tr>
                    {% for student in object_list %}
                <tr>
                    <td>{{ student.id }} </td>
                    <td><a href="{% url 'students:detail' student.id%}">{{ student.name }} {{ student.surname }}</a></td>
                    <td>{{ student.address }} </td>
                    <td>{{ student.skype }} </td>
                    <td> 
                        {% for courses in student.courses.all %}
                            <p><a href="{% url 'courses:detail' courses.id%}">{{ courses }}</a></p>
                        {% endfor %}   
                    </td>
                    <td><a href="{% url 'students:edit' student.id %}"><button type="button" class="btn btn-primary">Изменить</button></a></td>
                    <td><a href="{% url 'students:remove' student.id %}"><button type="button" class="btn btn-primary">Удалить</button></a></td>
                 </tr>
                  {% endfor %}
            </table>
            
            {% if is_paginated %}

               <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li><a href="?{{ course_id_url }}page={{ page_obj.previous_page_number }}"><< previous</a></li>
                    {% endif %}
                  
                   {% for page in paginator.page_range %}
                      {% if page == page_obj.number %}
                          <li class="active"><a href="">{{ page }}<span class="sr-only"></span></a></li>
                      {% else %}
                         <li><a href="?{{ course_id_url }}page={{ page }}">{{ page }}<span class="sr-only"></span></a></li>
                       {% endif %}
                   {% endfor %}

                
                    {% if page_obj.has_next %}
                        <li><a href="?{{ course_id_url }}page={{ page_obj.next_page_number }}">next >></a></li>
                     {% endif %}
                </ul>
            {% endif %}

          </div><!-- /.blog-post -->

{% endblock content %}