courses/urls.py
from django.conf.urls import url
from . import views

app_name = 'courses'
urlpatterns = [
url(r'^(?P<pk>\d+)/$', views.CourseDetailView.as_view(), name='detail'),
url(r'^add/$', views.CourseCreateView.as_view(), name='add'),
url(r'^edit/(?P<pk>\d+)/$', views.CourseUpdateView.as_view(), name='edit'),
url(r'^remove/(?P<pk>\d+)/$', views.CourseDeleteView.as_view(), name='remove'),
url(r'^(?P<pk>\d+)/add_lesson$', views.LessonCreateView.as_view(), name='add_lesson'),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

pybursa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import index, contact, student_list, student_detail
from feedbacks import views


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^contact/',  contact, name='contact'),
    url(r'^feedback/',  views.FeedbackView.as_view(), name='feedback'),
    url(r'^quadratic/', include('quadratic.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^courses/', include('courses.urls', namespace = 'courses', app_name='courses')),
    url(r'^students/', include('students.urls', namespace = 'students', app_name='students')),
    url(r'^coaches/', include('coaches.urls', namespace = 'coaches', app_name='coaches')),
    url(r'^admin/', admin.site.urls),
]

students/urls.py
from django.conf.urls import url
from . import views

app_name = 'students'
urlpatterns = [
url(r'^$', views.StudentListView.as_view(), name='list_view'),
url(r'^(?P<pk>\d+)/$', views.StudentDetailView.as_view(), name='detail'),
url(r'^add/$', views.StudentCreateView.as_view(), name='add'),
url(r'^edit/(?P<pk>\d+)/$', views.StudentUpdateView.as_view(), name='edit'),
url(r'^remove/(?P<pk>\d+)/$', views.StudentDeleteView.as_view(), name='remove'),
]

feedbacks/models.py
from django.db import models

class Feedback(models.Model):
    name=models.CharField(max_length=60)         
    subject=models.CharField(max_length=255)     
    message=models.TextField()     
    from_email=models.EmailField()
    create_date=models.DateTimeField(auto_now_add=True)    

feedbacks/forms.py
from feedbacks.models import Feedback
from django import forms

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        exclude = []

feedbacks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from feedbacks.models import Feedback
from .forms import FeedbackForm
from django.contrib import messages
from django.views.generic.edit import CreateView
from django.urls import reverse, reverse_lazy
from django.core.mail import send_mail
from django.conf import settings

import sendgrid
import os
from sendgrid.helpers.mail import *


class FeedbackView(CreateView):
    model = Feedback
    form_class = FeedbackForm
    template_name = 'feedback.html'
    success_url = reverse_lazy('feedback')
    
    def form_valid(self, form):
        response = super().form_valid(form)
        send_mail(form.cleaned_data['subject'], form.cleaned_data['message'], form.cleaned_data['from_email'], recipient_list=['vlyuda@mail.ru', 'kaluzhynova@gmail.com'])

   #               form.cleaned_data['from_email'], recipient_list=settings.ADMINS)
   #     messages.success(self.request, "Thank you for your feedback! We will keep in touch with you very soon!")


 #       sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('pybursalk'))
  #      from_email = Email(form.cleaned_data['from_email'])
  #      to_email = Email('kaluzhynova@gmail.com')
  #      subject = form.cleaned_data['subject']
  #      content = Content("text/plain", form.cleaned_data['message'])
  #      mail = Mail(from_email, subject, to_email, content)
  #      response = sg.client.mail.send.post(request_body=mail.get())
   #     print(response.status_code)
   #     print(response.body)
   #     print(response.headers)

        messages.success(self.request, "Thank you for your feedback! We will keep in touch with you very soon!")


        return response

 

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %} PyBursa {% endblock title %}</title>
  
    {% load static %}
    <!-- Bootstrap -->
    <link href="{% static 'css/style.css'%}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css'%}" rel="stylesheet">
    
  </head>
  <body>
 
<div class="container">
     <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
               
          <li class = {% block nav_class_index %}   {% endblock %}><a href="{% url 'index'%}">Главная</a></li>
          <li class = {% block nav_class_contact %} {% endblock %}><a href="{% url 'contact'%}">Контакты</a></li>
          <li class = {% block nav_class_student %} {% endblock %}><a href="{% url 'students:list_view' %}{% block nav_class_student_course %} {% endblock %}">Студенты</a></li>
          <li class = {% block nav_class_feedback %} {% endblock %}><a href="{% url 'feedback' %}">Обратная связь</a></li>
         
         </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  
    <!-- Main jumbotron for a primary marketing message or call to action -->
 
        
    <div class="container">

    {% block content %}    {% endblock content %}
    </div><!-- /.container -->


   
</div>

     <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.js' %}"></script>  

  </body>
</html>

templates/contact.html
{% extends "base.html" %}

{% block nav_class_contact %} active {% endblock %}

{% block title %} Контакты -PyBursa {% endblock title %}


{% block content %}
{% include "include/school_include.html" %}
   <div class="media">
  <div class="media-left">
     <img class ="media-object" src="../static/images/1.jpg" alt="Director">
  </div>
  <div class="media-body">
    <div class="contact">
      <h2 class="media-heading"><a href="{% url 'index'%}">Director</a> 
      </h2>
      <p> <b>Name:</b> Ivan Ivanov</p> 
      <p><b>Skype:</b> iivanov</p>
      <p><b>Email:</b> iivanov@gmail.com</p> 
      <p><b>Phone:</b> (000) 000-00-00</p>
    </div>
    <p>Some text Some text Some text Some text Some text Some text Some text Some text Some text Some text Some text Some text </p>
  </div>
</div>

<div class="media">
  <div class="media-left">
    <img class="media-object" src="../static/images/2.jpg" alt="Manager">
   </div>
  <div class=" media-body">
    
    <div class="contact">
      <h2 class="media-heading"><a href="{% url 'index'%}">Manager</a>  
      </h2>
      <p> <b>Name:</b> Ivan Ivanov</p> 
      <p><b>Skype:</b> iivanov</p>
      <p><b>Email:</b> iivanov@gmail.com</p> 
      <p><b>Phone:</b> (000) 000-00-00</p>
    </div>
   <p>Some text Some text Some text Some text Some text Some text Some text Some text Some text Some text Some text Some text </p>
  </div>
</div>

<div class="media">
  <div class="media-left">
    <img class="media-object" src="../static/images/3.jpg" alt="Founder">
  </div>
  <div class="media-body">
    <div class="contact">
      <h2 class="media-heading"><a href="{% url 'index'%}">Founder</a>  
      </h2>
      <p> <b>Name:</b> Ivan Ivanov</p> 
      <p><b>Skype:</b> iivanov</p>
      <p><b>Email:</b> iivanov@gmail.com</p> 
      <p><b>Phone:</b> (000) 000-00-00</p>
    </div>
    <p>Some text Some text Some text Some text Some text Some text Some text Some text Some text Some text Some text Some text </p>
   
   </div>
{% endblock content %}

templates/feedback.html
{% extends "base.html" %}

{% block title %} Обратная связь {% endblock title %}

{% block nav_class_feedback %} active {% endblock %}

{% block content %}

{% if messages %}
        <ul class="messages">
         <div class="jumbotron">
           {% for message in messages %}
             <li{% if message.tags %} class="{{ massage.tags }}" {% endif %}>{{ message }}</li>
           {% endfor %}
        </div>
        </ul>
     {% endif %}
      
 <div class="blog-post">

   <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value = "Отправить"/>
   </form>

{% endblock content %}

templates/index.html
{% extends "base.html" %}


{% block nav_class_index %} active {% endblock %}


{% block title %} Главная -PyBursa {% endblock title %}


{% block content %}
     {% include "include/school_include.html" %}

     {% if messages %}
        <ul class="messages">
         <div class="jumbotron">
           {% for message in messages %}
             <li{% if message.tags %} class="{{ massage.tags }}" {% endif %}>{{ message }}</li>
           {% endfor %}
        </div>
        </ul>
     {% endif %}

        <div class="blog-post">
            <h2>Наши курсы:</h2>

            <table class="table table-bordered"  style="width: 95%">
                <tr class="student_list">
                   <td>#</td>
                   <td>Курс</td>
                   <td>Описание</td>
                   <td></td>
                   <td></td>
                </tr>
                  {% for course in courses%}
                <tr>
                     <td>{{ forloop.counter }}</td>
                     <td><a href="{% url 'courses:detail' course.id%}">{{ course.name|upper }}</a> </td>
                     <td>{{ course.short_description|title }} </td>
                     <td><a href="{% url 'courses:edit' course.id %}"><button type="button" class="btn btn-primary">Изменить</button></a></td>
                     <td><a href="{% url 'courses:remove' course.id %}"><button type="button" class="btn btn-primary">Удалить</button></a></td>
                </tr>
                  {% endfor %}
            </table>
<p>
  <a href="{% url 'courses:add' %}"><button type="button" class="btn btn-primary">Добавить новый курс</button></a>
</p>
          </div><!-- /.blog-post -->
{% endblock content %}
