courses/urls.py
from django.conf.urls import url
from . import views

app_name = 'courses'
urlpatterns = [
url(r'^(?P<pk>\d+)/$', views.CourseDetailView.as_view(), name='detail'),
url(r'^add/$', views.CourseCreateView.as_view(), name='add'),
url(r'^edit/(?P<pk>\d+)/$', views.CourseUpdateView.as_view(), name='edit'),
url(r'^remove/(?P<pk>\d+)/$', views.CourseDeleteView.as_view(), name='remove'),
url(r'^(?P<pk>\d+)/add_lesson$', views.LessonCreateView.as_view(), name='add_lesson'),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

pybursa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import index, contact, student_list, student_detail
from feedbacks import views


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^contact/',  contact, name='contact'),
    url(r'^feedback/',  views.FeedbackView.as_view(), name='feedback'),
    url(r'^quadratic/', include('quadratic.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^courses/', include('courses.urls', namespace = 'courses', app_name='courses')),
    url(r'^students/', include('students.urls', namespace = 'students', app_name='students')),
    url(r'^coaches/', include('coaches.urls', namespace = 'coaches', app_name='coaches')),
    url(r'^admin/', admin.site.urls),
]

courses/models.py
from django.db import models
from django.conf import settings
from coaches.models import Coach

class Course(models.Model):
    name = models.CharField(max_length=255)
    short_description = models.CharField(max_length=255)     
    description = models.TextField(max_length=1255)      
    coach = models.ForeignKey(Coach, related_name = 'coach_courses', null=True, blank= True)
    assistant = models.ForeignKey(Coach, related_name = 'assistant_courses', null=True, blank= True)
    def __str__(self):
        return self.name


class Lesson(models.Model):
    subject = models.CharField(max_length=255)      
    description = models.TextField(max_length=1255)        
    course = models.ForeignKey(Course)  
    order = models.PositiveIntegerField()        
    def __str__(self):
        return self.subject

courses/forms.py
from courses.models import Course, Lesson
from django import forms

class CourseModelForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'short_description', 'description', 'coach', 'assistant']

class  LessonModelForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ['subject', 'description', 'course', 'order']

courses/views.py
from django.shortcuts import render, redirect
from courses.models import Course, Lesson
from courses.forms import CourseModelForm, LessonModelForm
from coaches.models import Coach
from django.http import HttpResponse, HttpResponseNotFound
from django.contrib import messages
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy

import logging
logger = logging.getLogger(__name__)

class CourseDetailView(DetailView):
    model = Course
    template_name = 'courses/detail.html'
    context_object_name = 'course'

    def get_context_data(self, **kwargs):
        logger.debug("Courses detail view has been debugged!")
        logger.info("Logger of courses detail view informs you!")        
        logger.warning("Logger of courses detail view warns you!")
        logger.error("Courses detail view went wrong!")
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']
        context['lessons'] = Lesson.objects.filter(course__id=pk)
        return context


class CourseCreateView(CreateView):
    model = Course
    form_class = CourseModelForm
    success_url = reverse_lazy('index')
    template_name = 'courses/add.html'
    context_object_name = 'course'
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Course {0} has been successfully added.".format(form.cleaned_data['name']))
        return response
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Course creation' 
        return context


class CourseUpdateView(UpdateView):
    model = Course
    form_class = CourseModelForm
    success_url = reverse_lazy('index')
    template_name = 'courses/edit.html'
    context_object_name = 'course'
    
    def get_success_url(self):
        super().get_success_url()
        pk = self.kwargs['pk']
        return reverse('courses:edit', args=(pk,))

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "The changes have been saved.")
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Course update' 
        return context


class CourseDeleteView(DeleteView):
    model = Course
    success_url = reverse_lazy('index')
    template_name = 'courses/remove.html'
    context_object_name = 'course'
    
    def delete(self, request, *args, **kwargs):
        response = super().delete(self, request, *args, **kwargs)
        messages.success(self.request, "Course {0} has been deleted.".format(
            self.object.name))
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Course deletion' 
        return context


class LessonCreateView(CreateView):
    model = Lesson
    form_class = LessonModelForm
    success_url = reverse_lazy('index')
    template_name = 'courses/add_lesson.html'
    context_object_name = 'lessons'
    
    def get_success_url(self):
        super().get_success_url()
        pk = self.kwargs['pk']
        return reverse('courses:detail', args=(pk,))

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Lesson {0} has been successfully added.".format(form.cleaned_data['subject']))
        return response
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Lesson creation' 
        return context

templates/courses/add.html
{% extends "base.html" %}

{% block title %} {{ title }} {% endblock title %}

{% block content %}
      
 <div class="blog-post">
  <h2>{{ title }}</h2>

   <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value = "Создать"/>
   </form>

{% endblock content %}

templates/courses/add_lesson.html
{% extends "base.html" %}

{% block title %} Создание нового занятия {% endblock title %}

{% block content %}
      
 <div class="blog-post">
  <h2>Создание нового занятия </h2>

   <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value = "Создать"/>
   </form>

{% endblock content %}

templates/courses/detail.html
{% extends "base.html" %}

{% block title %} Курс {% endblock title %}

{% block nav_class_student_course %}?course_id={{ course.id }}{% endblock %}


{% block content %}
  {% if messages %}
      <ul class="messages">
          <div class="jumbotron">
              {% for message in messages %}
                <li{% if message.tags %} class="{{ massage.tags }}" {% endif %}>{{ message }}</li>
              {% endfor %}
          </div>
      </ul>
  {% endif %}


  <div class="blog-header">
      <h1 class="blog-title">{{ course.name }} </h1>
      <p>{{ course.description|truncatechars:32  }} </p>
  </div>

  <div class="blog-post">

   <h2>Преподаватели</h2>
      {% if course.coach %} 
          <table class="table table-bordered" style="width: 95%">
            <tr class="student_list">
                <td>Учитель</td>
            </tr>
            <tr>
                <td><p><a href="{% url 'coaches:detail' course.coach.id %}">{{ course.coach.user.first_name }}  {{ course.coach.user.last_name }}</a></p> 
                <p> {{ course.coach.description }}</p>
                </td>
            </tr>
          </table>
      {% endif %}

      {% if course.assistant %} 
          <table class="table table-bordered" style="width: 95%">
            <tr class="student_list">
               <td>Ассистент</td>
            </tr>
            <tr>
              <td>
                 <p><a href="{% url 'coaches:detail' course.assistant.id %}">{{ course.assistant.user.first_name }}  {{ course.assistant.user.last_name }}</a></p> 
                 <p> {{ course.assistant.description }}</p>
              </td>
            </tr>
          </table>
      {% endif %}
  </div><!-- /.blog-post -->
 
  <div class="blog-post">
    <h2>План курса</h2>
      <p>
        <a href="{% url 'courses:add_lesson' course.id%}"><button type="button" class="btn btn-primary">Создание нового занятия </button></a>
      </p>

    <table class="table table-bordered" style="width: 95%">
       <tr class="student_list">
         <td>#</td>
         <td>Тема</td>
         <td>Описание</td>
       </tr>
          {% for lessons in lessons%}
       <tr>
         <td>{{ lessons.order }} </td>
         <td>{{ lessons.subject }} </td>
         <td>{{ lessons.description }} </td>
      </tr>
          {% endfor %}
    </table>
      <p>  <a href="{% url 'courses:remove' course.id %}"><button type="button" class="btn btn-primary">Удалить курс</button></a> </p>
  </div><!-- /.blog-post -->

{% endblock content %}



templates/courses/edit.html
{% extends "base.html" %}

{% block title %} {{ title }} {% endblock title %}

{% block content %}

{% if messages %}
        <ul class="messages">
         <div class="jumbotron">
           {% for message in messages %}
             <li{% if message.tags %} class="{{ massage.tags }}" {% endif %}>{{ message }}</li>
           {% endfor %}
        </div>
        </ul>
     {% endif %}
      
 <div class="blog-post">
  <h2>{{ title }}</h2>

   <form method="post">
     {% csrf_token %}
     {{ form.as_p }}
     <input type="submit" value = "Изменить"/>
   </form>

{% endblock content %}

templates/courses/remove.html
{% extends "base.html" %}

{% block title %} {{ title }} {% endblock title %}

{% block content %}
<h2>{{ title }}</h2>
      
 <div class="blog-post">
  <h2>Курс {{ course.name }} будет удален </h2>

   <form method="post">
     {% csrf_token %}
     <input type="submit" value = "Удалить"/>
   </form>

{% endblock content %}